// Blog posts. PILLARS keys: seo | ai | content | craft | notice | us
export const PILLARS = {
  seo: { no: '01', label: 'SEO', href: 'Pillar.dc.html?p=seo', card: 'Technical fixes, on-page work, and the fundamentals that still drive organic traffic.', t1: 'Rank where they ', word: 'still', t2: ' search.', desc: 'Google still sends more buyers than every other channel combined, and most of what wins there is unglamorous: clean structure, intent-matched pages, titles written for the click. This folder holds the technical fixes, on-page optimization, and fundamentals that keep organic traffic compounding.' },
  ai: { no: '02', label: 'AI Search', href: 'Pillar.dc.html?p=ai', card: 'How brands show up when a machine does the recommending.', t1: 'Be the answer the ', word: 'machine', t2: ' gives.', desc: 'Your next buyer may never see your homepage. They\u2019ll see what ChatGPT, Perplexity, and Google\u2019s AI Overviews say about you, built from whatever those systems chose to cite. This folder is about getting found, quoted, and recommended when a machine assembles the answer.' },
  content: { no: '03', label: 'Content Marketing', href: 'Pillar.dc.html?p=content', card: 'Strategy, distribution, and an owned audience that turns writing into pipeline.', t1: 'Content that turns into ', word: 'pipeline', t2: '.', desc: 'Content as a growth channel, not a calendar to feed. Strategy, distribution, and building an owned audience, written for the person who signs and the person who forwards it to them.' },
  craft: { no: '04', label: 'The Craft', href: 'Pillar.dc.html?p=craft', card: 'Writing, voice, and editing. Good enough that people and machines want to cite it.', t1: 'The ', word: 'craft', t2: ' of it.', desc: 'Content as a craft: the writing, voice, and editing underneath everything else we publish. What makes a piece good enough that people finish it and machines cite it.' },
  notice: { no: '05', label: 'Did You Notice', href: 'Pillar.dc.html?p=notice', card: 'Small, clever, overlooked details on real websites, noticed out loud.', t1: 'Did you ', word: 'notice', t2: '...?', desc: 'An observation series. We spot the small, clever, or overlooked details on real websites, critique where it\u2019s earned, and sketch what might have worked better. Every piece starts as a \u201cdid you notice...\u201d moment, because that\u2019s how we talk to each other anyway.' },
  us: { no: '06', label: 'Between Us', href: 'Pillar.dc.html?p=us', card: 'Candid, opinionated musings on the industry. Every piece opens the same way.', t1: 'Between ', word: 'us', t2: ',', desc: 'Candid, opinionated musings on the industry we work in. Every piece opens with \u201cBetween us, ...\u201d and then says the thing agencies usually save for the second drink.' }
};

export const AUTHORS = {
  tim: { key: 'tim', name: 'Timothy Agbola', role: 'Partner \u00b7 Strategy', slotId: 'photo-tim', photo: 'assets/tim.png', linkedin: 'https://www.linkedin.com/in/timothy-agbola-7092571b5/', bio: 'One half of The Other Guys. Sets the strategy, carries the heavy ideas, and argues for the reader in every draft. Before this he built content at iGotAnOffer and Launchspace, where he got obsessed with one question: why does distribution get all the credit when the writing does the work?', beat: 'Writes mostly about AI search, answer engines, and what earns a citation.' },
  nelson: { key: 'nelson', name: 'Nelson Ansah', role: 'Partner \u00b7 Execution', slotId: 'photo-nelson', photo: 'assets/nelson.png', linkedin: 'https://www.linkedin.com/in/thenelsonansah/', bio: 'The other half. Turns the plan into published work, on time, at the bar. Has shipped for Sprig, ClickUp, Skillzy, and Synthesia, mostly turning product roadmaps into stories buyers finish.', beat: 'Writes mostly about buyer-first strategy and the unglamorous craft of shipping.' }
};

export const POSTS = [
  { id: 'between-us-retainers', pillar: 'us', title: 'Between Us, Most Retainers Are Rent', blurb: 'Between us, a lot of monthly fees buy a standing meeting, not standing work. Here\u2019s how to tell which one you\u2019re paying for.', author: 'Nelson Ansah', date: 'Jul 22, 2026', mins: 4, ill: 'Pencil drawing: two chairs leaned close together, one whispering to the other' },
  { id: 'ai-citations', pillar: 'ai', type: 'report', title: 'What AI Search Cites (We Checked 200 Answers)', blurb: 'We asked ChatGPT, Perplexity, and Google AI Mode the questions your buyers ask, then traced every citation. The pattern is uncomfortable for most content teams.', author: 'Timothy Agbola', date: 'Jul 14, 2026', mins: 7, ill: 'Pencil drawing: a detective with a magnifying glass inspecting a robot\u2019s footnotes' },
  { id: 'notice-empty-state', pillar: 'notice', title: 'Did You Notice What Stripe Hides in Its 404 Page?', blurb: 'A dead end most teams ignore, turned into the most charming page on the site. We break down why it works and what everyone else leaves on the table.', author: 'Nelson Ansah', date: 'Jun 30, 2026', mins: 4, ill: 'Pencil drawing: a magnifying glass hovering over the corner of a webpage' },
  { id: 'good-writing-work', pillar: 'craft', title: 'Good Writing Was Always This Much Work', blurb: 'AI didn\u2019t change the rules. It just made it impossible to pretend we were following them.', author: 'Timothy Agbola', date: 'Jun 17, 2026', mins: 5, ill: 'Pencil drawing: a writer buried under drafts at a desk with a grandfather clock' },
  { id: 'ai-didnt-kill', pillar: 'ai', title: 'AI Didn\u2019t Kill Good Writing Because There Wasn\u2019t Much to Kill', blurb: 'AI made it really obvious how much of our \u201ccontent marketing\u201d was already a zombie shambling around, moaning \u201c10 tips... must... rank...\u201d', author: 'Timothy Agbola', date: 'Jun 17, 2026', mins: 3, ill: 'Pencil drawing: a friendly robot holding a paintbrush over a pile of identical listicles' },
  { id: 'seo-unsexy-fixes', pillar: 'seo', title: 'The Unsexy SEO Fixes That Paid for Themselves in a Quarter', blurb: 'No hacks, no schemes. Internal links, titles rewritten for the click, and pruning the pages nobody asked for. The boring stuff, ranked by payback.', author: 'Timothy Agbola', date: 'May 5, 2026', mins: 6, ill: 'Pencil drawing: a plumber tightening pipes underneath a giant search bar' },
  { id: 'signs-and-doesnt', pillar: 'content', title: 'Write for the Person Who Signs, and the One Who Doesn\u2019t', blurb: 'Your champion forwards the post. Their CFO reads two paragraphs. Both need to find what they came for.', author: 'Nelson Ansah', date: 'Apr 22, 2026', mins: 6, ill: 'Pencil drawing: two readers sharing one newspaper, each looking at a different page' },
  { id: 'client-first-30', pillar: 'craft', title: 'What We Do When a Client Hires Us', blurb: 'A peek into those first 30 days here at The Other Guys. And a breakdown of our favorite client onboarding question.', author: 'Nelson Ansah', date: 'Jan 30, 2026', mins: 3, ill: 'Pencil drawing: three people huddled over a table labeled \u201cthe narrative spine\u201d' },
  { id: 'january-dont-publish', pillar: 'content', title: 'It\u2019s January. Please Don\u2019t Publish Anything Yet.', blurb: 'Give this a read. It\u2019ll make your January(s) so much better.', author: 'Nelson Ansah', date: 'Jan 30, 2026', mins: 3, ill: 'Pencil drawing: a typewriter tangled in bare winter branches, page reading \u201cJanuary\u201d' },
  { id: 'content-cyborg', pillar: 'ai', title: 'The Content Cyborg + AI Musings', blurb: 'You tried going full human. Then you tried going full robot. Here\u2019s the one thing left that truly wins content for your biz.', author: 'Timothy Agbola', date: 'Jan 30, 2026', mins: 3, ill: 'Pencil drawing: a profile of a head with gears and a pencil where the brain goes' },
  { id: 'aeo-manners', pillar: 'seo', title: 'AEO Is Just SEO With Better Manners', blurb: 'Answer engines reward the things good editors always did. Clear claims, named sources, actual expertise. The checklist is shorter than the acronym suggests.', author: 'Timothy Agbola', date: 'Nov 12, 2025', mins: 5, ill: 'Pencil drawing: a robot politely holding a door open for a stack of documents' },
  { id: 'other-way', pillar: 'content', title: 'The Other Way: Our Content Strategy', blurb: 'Six months ago, Tim and I made a bet that would either validate everything we believed about content marketing or prove us spectacularly wrong.', author: 'Nelson Ansah', date: 'Oct 7, 2025', mins: 3, ill: 'Pencil drawing: a winding path up a hill with signposts reading \u201cclear strategy, quality, impact\u201d' },
  { id: 'case-against-tog', pillar: 'us', title: 'Between Us, Here\u2019s the Case Against The Other Guys', blurb: 'We\u2019re going to make a strong case for why you shouldn\u2019t hire us.', author: 'Nelson Ansah', date: 'Oct 7, 2025', mins: 3, ill: 'Pencil drawing: a robot lawyer pointing at a confused jury of doodles' },
  { id: 'sacred-rule', pillar: 'content', title: 'The One Content Marketing Tweak That Can Drive 1,000+ Users (By Breaking a Sacred Rule)', blurb: 'Most content advice tells you to \u201cwrite for your audience.\u201d Here\u2019s why that mindset quietly kills pipeline, and how writing for buyers instead can turn a single blog post into a revenue-generating asset.', author: 'Nelson Ansah', date: 'Jul 25, 2025', mins: 3, ill: 'Pencil drawing: a stone tablet of \u201csacred rules\u201d cracking, users pouring out' },
  { id: 'why-here', pillar: 'craft', title: 'Why The &#!$ Are We Here?', blurb: 'Up until a week ago, we weren\u2019t an agency. Nine sprint sessions and sleepless nights later, we launched The Other Guys.', author: 'Nelson Ansah', date: 'Jul 25, 2025', mins: 3, ill: 'Pencil drawing: two figures nailing a hand-painted \u201copen\u201d sign above a door' }
];
